# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version here
      - image: circleci/elixir:1.5.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "mix.lock" }}
            - v1-dependency-cache
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run:
          command: mix compile
          environment:
            MIX_ENV: test
      - save_cache:
          key: v1-dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - run: mix test
      - run: mix docs
  publish_docs:
    docker:
      # specify the version here
      - image: circleci/elixir:1.5.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "mix.lock" }}
            - v1-dependency-cache
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run:
          command: mix compile
          environment:
            MIX_ENV: test
      - save_cache:
          key: v1-dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - run: mix docs
      - run: scripts/update_master_documentation.sh
  code-quality:
    docker:
      # specify the version here
      - image: circleci/elixir:1.5.2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-plt-cache-{{ checksum "mix.lock" }}
            - v1-plt-cache
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run:
          command: mix compile
          environment:
            MIX_ENV: test
      - run: mix dialyzer --plt
      - save_cache:
          key: v1-plt-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix
      - run: mix credo
      - run: mix dogma
      - run: mix dialyzer
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish_docs:
          filters:
            branches:
              only: master
      - code-quality:
          requires:
            - build
